services:
  - type: web
    name: my-fastapi-app
    env: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
